// <auto-generated>
// This code was generated by the API Client Generator skill.
// Changes to this file may be overwritten when the code is regenerated.
// </auto-generated>

#nullable enable

using System.Net.Http.Json;
using System.Text.Json;

namespace {{namespace}}.Clients;

/// <summary>
/// Client for {{tag}} API operations.
/// {{description}}
/// </summary>
public class {{tag}}Client
{
    private readonly HttpClient _httpClient;
    private readonly JsonSerializerOptions _jsonOptions;

    /// <summary>
    /// Initializes a new instance of <see cref="{{tag}}Client"/>.
    /// </summary>
    /// <param name="httpClient">The HTTP client to use for requests.</param>
    public {{tag}}Client(HttpClient httpClient)
    {
        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        _jsonOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            PropertyNameCaseInsensitive = true
        };
    }

{{#operations}}
    /// <summary>
    /// {{summary}}
    /// </summary>
    /// <remarks>
    /// {{description}}
    /// </remarks>
{{#parameters}}
    /// <param name="{{name}}">{{description}}</param>
{{/parameters}}
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>{{returnDescription}}</returns>
    /// <exception cref="HttpRequestException">Thrown when the request fails.</exception>
    public async Task<{{returnType}}> {{operationId}}Async(
{{#parameters}}
        {{type}} {{name}},
{{/parameters}}
        CancellationToken cancellationToken = default)
    {
        var requestUri = $"{{path}}";

{{#hasBody}}
        var response = await _httpClient.{{httpMethod}}AsJsonAsync(
            requestUri,
            {{bodyParameter}},
            _jsonOptions,
            cancellationToken);
{{/hasBody}}
{{^hasBody}}
        var response = await _httpClient.{{httpMethod}}Async(
            requestUri,
            cancellationToken);
{{/hasBody}}

        response.EnsureSuccessStatusCode();

{{#hasReturnType}}
        return await response.Content.ReadFromJsonAsync<{{returnType}}>(
            _jsonOptions,
            cancellationToken)
            ?? throw new InvalidOperationException("Response was null");
{{/hasReturnType}}
{{^hasReturnType}}
        return;
{{/hasReturnType}}
    }

{{/operations}}
}
